-- Run this entire file in the new Supabase project's SQL Editor.

create table if not exists public.coffee_orders (
    id bigint generated by default as identity primary key,
    product_name text not null,
    customer_name text not null,
    special_request text not null default '',
    status text not null default 'preparing'
        check (status in ('preparing', 'ready')),
    created_at timestamptz not null default now()
);

create index if not exists coffee_orders_status_created_at_idx
    on public.coffee_orders (status, created_at desc);

alter table public.coffee_orders enable row level security;

drop policy if exists "Public can read coffee orders" on public.coffee_orders;
create policy "Public can read coffee orders"
    on public.coffee_orders
    for select
    to anon, authenticated
    using (true);

drop policy if exists "Public can create coffee orders" on public.coffee_orders;
create policy "Public can create coffee orders"
    on public.coffee_orders
    for insert
    to anon, authenticated
    with check (
        status = 'preparing'
        and length(trim(product_name)) > 0
        and length(trim(customer_name)) > 0
    );

drop policy if exists "Public can update coffee orders" on public.coffee_orders;
create policy "Public can update coffee orders"
    on public.coffee_orders
    for update
    to anon, authenticated
    using (true)
    with check (status in ('preparing', 'ready'));

drop policy if exists "Public can delete coffee orders" on public.coffee_orders;
create policy "Public can delete coffee orders"
    on public.coffee_orders
    for delete
    to anon, authenticated
    using (true);

grant select, insert, delete on public.coffee_orders to anon, authenticated;
grant update (status) on public.coffee_orders to anon, authenticated;
grant usage, select on sequence public.coffee_orders_id_seq to anon, authenticated;

do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'coffee_orders'
    ) then
        alter publication supabase_realtime add table public.coffee_orders;
    end if;
end
$$;
